
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_BaseProxyBase_HXX_
#define INCLUDE_vnx_BaseProxyBase_HXX_

#include <vnx/package.hxx>
#include <vnx/Hash64.hpp>
#include <vnx/Module.h>
#include <vnx/Session.hxx>
#include <vnx/TopicPtr.hpp>


namespace vnx {

class VNX_EXPORT BaseProxyBase : public ::vnx::Module {
public:
	
	std::string address;
	std::pair<std::string, std::string> auto_login;
	std::vector<::vnx::TopicPtr> import_list;
	std::vector<::vnx::TopicPtr> export_list;
	std::vector<std::string> forward_list;
	std::vector<::vnx::Hash64> tunnel_list;
	std::map<::vnx::TopicPtr, ::vnx::TopicPtr> import_map;
	std::map<::vnx::TopicPtr, ::vnx::TopicPtr> export_map;
	::vnx::Hash64 receive_tunnel;
	::vnx::Hash64 request_tunnel;
	vnx::bool_t auto_import = false;
	vnx::bool_t time_sync = false;
	vnx::bool_t allow_login = true;
	vnx::bool_t use_authentication = false;
	vnx::bool_t block_until_connect = true;
	vnx::bool_t block_until_reconnect = false;
	int32_t max_queue_ms = 100;
	int32_t max_queue_size = 1000;
	int32_t max_hop_count = 10;
	int32_t recv_buffer_size = 0;
	int32_t send_buffer_size = 131072;
	std::string default_access = "DEFAULT";
	
	typedef ::vnx::Module Super;
	
	static const vnx::Hash64 VNX_TYPE_HASH;
	static const vnx::Hash64 VNX_CODE_HASH;
	
	static constexpr uint64_t VNX_TYPE_ID = 0xd8241ff9082104f5ull;
	
	BaseProxyBase(const std::string& _vnx_name);
	
	vnx::Hash64 get_type_hash() const override;
	std::string get_type_name() const override;
	const vnx::TypeCode* get_type_code() const override;
	
	void read(std::istream& _in) override;
	void write(std::ostream& _out) const override;
	
	template<typename T>
	void accept_generic(T& _visitor) const;
	void accept(vnx::Visitor& _visitor) const override;
	
	vnx::Object to_object() const override;
	void from_object(const vnx::Object& object) override;
	
	vnx::Variant get_field(const std::string& name) const override;
	void set_field(const std::string& name, const vnx::Variant& value) override;
	
	friend std::ostream& operator<<(std::ostream& _out, const BaseProxyBase& _value);
	friend std::istream& operator>>(std::istream& _in, BaseProxyBase& _value);
	
	static const vnx::TypeCode* static_get_type_code();
	static std::shared_ptr<vnx::TypeCode> static_create_type_code();
	
protected:
	using Super::handle;
	
	virtual void login_async(const std::string& name, const std::string& password, const vnx::request_id_t& _request_id) const = 0;
	void login_async_return(const vnx::request_id_t& _request_id, const std::shared_ptr<const ::vnx::Session>& _ret_0) const;
	virtual void enable_import(const std::string& topic_name) = 0;
	virtual void disable_import(const std::string& topic_name) = 0;
	virtual void enable_export(const std::string& topic_name) = 0;
	virtual void disable_export(const std::string& topic_name) = 0;
	virtual void enable_forward(const std::string& service_name, const int32_t& max_queue_ms, const int32_t& max_queue_size) = 0;
	virtual void disable_forward(const std::string& service_name) = 0;
	virtual void enable_tunnel(const ::vnx::Hash64& tunnel_addr, const int32_t& max_queue_ms, const int32_t& max_queue_size) = 0;
	virtual void disable_tunnel(const ::vnx::Hash64& tunnel_addr) = 0;
	virtual std::shared_ptr<const ::vnx::Session> get_session() const = 0;
	virtual void wait_on_connect_async(const vnx::request_id_t& _request_id) const = 0;
	void wait_on_connect_async_return(const vnx::request_id_t& _request_id, const ::vnx::Hash64& _ret_0) const;
	virtual void wait_on_disconnect_async(const vnx::request_id_t& _request_id) const = 0;
	void wait_on_disconnect_async_return(const vnx::request_id_t& _request_id, const ::vnx::Hash64& _ret_0) const;
	virtual void on_connect() = 0;
	virtual void on_disconnect() = 0;
	virtual void on_remote_connect(const ::vnx::Hash64& process_id) = 0;
	virtual void on_login(const std::string& name, const std::string& password) = 0;
	virtual void on_remote_login(std::shared_ptr<const ::vnx::Session> remote_session) = 0;
	
	void vnx_handle_switch(std::shared_ptr<const vnx::Value> _value) override;
	std::shared_ptr<vnx::Value> vnx_call_switch(std::shared_ptr<const vnx::Value> _method, const vnx::request_id_t& _request_id) override;
	
};

template<typename T>
void BaseProxyBase::accept_generic(T& _visitor) const {
	_visitor.template type_begin<BaseProxyBase>(22);
	_visitor.type_field("address", 0); _visitor.accept(address);
	_visitor.type_field("auto_login", 1); _visitor.accept(auto_login);
	_visitor.type_field("import_list", 2); _visitor.accept(import_list);
	_visitor.type_field("export_list", 3); _visitor.accept(export_list);
	_visitor.type_field("forward_list", 4); _visitor.accept(forward_list);
	_visitor.type_field("tunnel_list", 5); _visitor.accept(tunnel_list);
	_visitor.type_field("import_map", 6); _visitor.accept(import_map);
	_visitor.type_field("export_map", 7); _visitor.accept(export_map);
	_visitor.type_field("receive_tunnel", 8); _visitor.accept(receive_tunnel);
	_visitor.type_field("request_tunnel", 9); _visitor.accept(request_tunnel);
	_visitor.type_field("auto_import", 10); _visitor.accept(auto_import);
	_visitor.type_field("time_sync", 11); _visitor.accept(time_sync);
	_visitor.type_field("allow_login", 12); _visitor.accept(allow_login);
	_visitor.type_field("use_authentication", 13); _visitor.accept(use_authentication);
	_visitor.type_field("block_until_connect", 14); _visitor.accept(block_until_connect);
	_visitor.type_field("block_until_reconnect", 15); _visitor.accept(block_until_reconnect);
	_visitor.type_field("max_queue_ms", 16); _visitor.accept(max_queue_ms);
	_visitor.type_field("max_queue_size", 17); _visitor.accept(max_queue_size);
	_visitor.type_field("max_hop_count", 18); _visitor.accept(max_hop_count);
	_visitor.type_field("recv_buffer_size", 19); _visitor.accept(recv_buffer_size);
	_visitor.type_field("send_buffer_size", 20); _visitor.accept(send_buffer_size);
	_visitor.type_field("default_access", 21); _visitor.accept(default_access);
	_visitor.template type_end<BaseProxyBase>(22);
}


} // namespace vnx


namespace vnx {

} // vnx

#endif // INCLUDE_vnx_BaseProxyBase_HXX_
