
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_Frame_HXX_
#define INCLUDE_vnx_Frame_HXX_

#include <vnx/package.hxx>
#include <vnx/Hash64.hpp>
#include <vnx/Message.hxx>
#include <vnx/Value.h>


namespace vnx {

class VNX_EXPORT Frame : public ::vnx::Message {
public:
	
	::vnx::Hash64 src_mac;
	::vnx::Hash64 dst_mac;
	uint64_t seq_num = 0;
	std::shared_ptr<const ::vnx::Value> value;
	
	typedef ::vnx::Message Super;
	
	static const vnx::Hash64 VNX_TYPE_HASH;
	static const vnx::Hash64 VNX_CODE_HASH;
	
	static constexpr uint64_t VNX_TYPE_ID = 0x2bcfeea96d21ae9bull;
	
	Frame() {}
	
	vnx::Hash64 get_type_hash() const override;
	std::string get_type_name() const override;
	const vnx::TypeCode* get_type_code() const override;
	
	static std::shared_ptr<Frame> create();
	std::shared_ptr<vnx::Value> clone() const override;
	
	void read(vnx::TypeInput& _in, const vnx::TypeCode* _type_code, const uint16_t* _code) override;
	void write(vnx::TypeOutput& _out, const vnx::TypeCode* _type_code, const uint16_t* _code) const override;
	
	void read(std::istream& _in) override;
	void write(std::ostream& _out) const override;
	
	template<typename T>
	void accept_generic(T& _visitor) const;
	void accept(vnx::Visitor& _visitor) const override;
	
	vnx::Object to_object() const override;
	void from_object(const vnx::Object& object) override;
	
	vnx::Variant get_field(const std::string& name) const override;
	void set_field(const std::string& name, const vnx::Variant& value) override;
	
	friend std::ostream& operator<<(std::ostream& _out, const Frame& _value);
	friend std::istream& operator>>(std::istream& _in, Frame& _value);
	
	static const vnx::TypeCode* static_get_type_code();
	static std::shared_ptr<vnx::TypeCode> static_create_type_code();
	
protected:
	std::shared_ptr<vnx::Value> vnx_call_switch(std::shared_ptr<const vnx::Value> _method) override;
	
};

template<typename T>
void Frame::accept_generic(T& _visitor) const {
	_visitor.template type_begin<Frame>(7);
	_visitor.type_field("stream", 0); _visitor.accept(stream);
	_visitor.type_field("flags", 1); _visitor.accept(flags);
	_visitor.type_field("hop_count", 2); _visitor.accept(hop_count);
	_visitor.type_field("src_mac", 3); _visitor.accept(src_mac);
	_visitor.type_field("dst_mac", 4); _visitor.accept(dst_mac);
	_visitor.type_field("seq_num", 5); _visitor.accept(seq_num);
	_visitor.type_field("value", 6); _visitor.accept(value);
	_visitor.template type_end<Frame>(7);
}


} // namespace vnx


namespace vnx {

} // vnx

#endif // INCLUDE_vnx_Frame_HXX_
