
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_GatewayInterface_CLIENT_HXX_
#define INCLUDE_vnx_GatewayInterface_CLIENT_HXX_

#include <vnx/Client.h>
#include <vnx/Request.hxx>


namespace vnx {

class GatewayInterfaceClient : public vnx::Client {
public:
	GatewayInterfaceClient(const std::string& service_name);
	
	GatewayInterfaceClient(vnx::Hash64 service_addr);
	
	void forward(std::shared_ptr<const ::vnx::Request> request = nullptr);
	
	void forward_async(std::shared_ptr<const ::vnx::Request> request = nullptr);
	
};


} // namespace vnx

#endif // INCLUDE_vnx_GatewayInterface_CLIENT_HXX_
