
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_JRPC_Request_HXX_
#define INCLUDE_vnx_JRPC_Request_HXX_

#include <vnx/package.hxx>
#include <vnx/JRPC_Notification.hxx>
#include <vnx/Variant.hpp>


namespace vnx {

class VNX_EXPORT JRPC_Request : public ::vnx::JRPC_Notification {
public:
	
	::vnx::Variant id;
	
	typedef ::vnx::JRPC_Notification Super;
	
	static const vnx::Hash64 VNX_TYPE_HASH;
	static const vnx::Hash64 VNX_CODE_HASH;
	
	static constexpr uint64_t VNX_TYPE_ID = 0x3fa720cce7b7a1d5ull;
	
	JRPC_Request() {}
	
	vnx::Hash64 get_type_hash() const override;
	std::string get_type_name() const override;
	const vnx::TypeCode* get_type_code() const override;
	
	virtual vnx::bool_t is_request_object() const;
	virtual vnx::bool_t is_request() const;
	virtual vnx::bool_t is_notification() const;
	
	static std::shared_ptr<JRPC_Request> create();
	std::shared_ptr<vnx::Value> clone() const override;
	
	void read(vnx::TypeInput& _in, const vnx::TypeCode* _type_code, const uint16_t* _code) override;
	void write(vnx::TypeOutput& _out, const vnx::TypeCode* _type_code, const uint16_t* _code) const override;
	
	void read(std::istream& _in) override;
	void write(std::ostream& _out) const override;
	
	template<typename T>
	void accept_generic(T& _visitor) const;
	void accept(vnx::Visitor& _visitor) const override;
	
	vnx::Object to_object() const override;
	void from_object(const vnx::Object& object) override;
	
	vnx::Variant get_field(const std::string& name) const override;
	void set_field(const std::string& name, const vnx::Variant& value) override;
	
	friend std::ostream& operator<<(std::ostream& _out, const JRPC_Request& _value);
	friend std::istream& operator>>(std::istream& _in, JRPC_Request& _value);
	
	static const vnx::TypeCode* static_get_type_code();
	static std::shared_ptr<vnx::TypeCode> static_create_type_code();
	
protected:
	std::shared_ptr<vnx::Value> vnx_call_switch(std::shared_ptr<const vnx::Value> _method) override;
	
};

template<typename T>
void JRPC_Request::accept_generic(T& _visitor) const {
	_visitor.template type_begin<JRPC_Request>(4);
	_visitor.type_field("jsonrpc", 0); _visitor.accept(jsonrpc);
	_visitor.type_field("method", 1); _visitor.accept(method);
	_visitor.type_field("params", 2); _visitor.accept(params);
	_visitor.type_field("id", 3); _visitor.accept(id);
	_visitor.template type_end<JRPC_Request>(4);
}


} // namespace vnx


namespace vnx {

} // vnx

#endif // INCLUDE_vnx_JRPC_Request_HXX_
