
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_ModuleInterface_HXX_
#define INCLUDE_vnx_ModuleInterface_HXX_

#include <vnx/Type.h>
#include <vnx/package.hxx>
#include <vnx/ModuleInfo.hxx>
#include <vnx/Object.hpp>
#include <vnx/TypeCode.hpp>
#include <vnx/Variant.hpp>


namespace vnx {

struct VNX_EXPORT ModuleInterface {
	
	
	
	static const vnx::Hash64 VNX_TYPE_HASH;
	static const vnx::Hash64 VNX_CODE_HASH;
	
	static constexpr uint64_t VNX_TYPE_ID = 0xe189eb244fe14948ull;
	
	ModuleInterface() {}
	
};


} // namespace vnx


namespace vnx {

} // vnx

#endif // INCLUDE_vnx_ModuleInterface_HXX_
