
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_ProxyInterface_disable_tunnel_HXX_
#define INCLUDE_vnx_ProxyInterface_disable_tunnel_HXX_

#include <vnx/package.hxx>
#include <vnx/Hash64.hpp>
#include <vnx/Value.h>


namespace vnx {

class VNX_EXPORT ProxyInterface_disable_tunnel : public ::vnx::Value {
public:
	
	::vnx::Hash64 tunnel_addr;
	
	typedef ::vnx::Value Super;
	
	static const vnx::Hash64 VNX_TYPE_HASH;
	static const vnx::Hash64 VNX_CODE_HASH;
	
	static constexpr uint64_t VNX_TYPE_ID = 0xb9a7abaf9d00b54bull;
	
	ProxyInterface_disable_tunnel() {}
	
	vnx::Hash64 get_type_hash() const override;
	std::string get_type_name() const override;
	const vnx::TypeCode* get_type_code() const override;
	
	static std::shared_ptr<ProxyInterface_disable_tunnel> create();
	std::shared_ptr<vnx::Value> clone() const override;
	
	void read(vnx::TypeInput& _in, const vnx::TypeCode* _type_code, const uint16_t* _code) override;
	void write(vnx::TypeOutput& _out, const vnx::TypeCode* _type_code, const uint16_t* _code) const override;
	
	void read(std::istream& _in) override;
	void write(std::ostream& _out) const override;
	
	template<typename T>
	void accept_generic(T& _visitor) const;
	void accept(vnx::Visitor& _visitor) const override;
	
	vnx::Object to_object() const override;
	void from_object(const vnx::Object& object) override;
	
	vnx::Variant get_field(const std::string& name) const override;
	void set_field(const std::string& name, const vnx::Variant& value) override;
	
	friend std::ostream& operator<<(std::ostream& _out, const ProxyInterface_disable_tunnel& _value);
	friend std::istream& operator>>(std::istream& _in, ProxyInterface_disable_tunnel& _value);
	
	static const vnx::TypeCode* static_get_type_code();
	static std::shared_ptr<vnx::TypeCode> static_create_type_code();
	
};

template<typename T>
void ProxyInterface_disable_tunnel::accept_generic(T& _visitor) const {
	_visitor.template type_begin<ProxyInterface_disable_tunnel>(1);
	_visitor.type_field("tunnel_addr", 0); _visitor.accept(tunnel_addr);
	_visitor.template type_end<ProxyInterface_disable_tunnel>(1);
}


} // namespace vnx


namespace vnx {

} // vnx

#endif // INCLUDE_vnx_ProxyInterface_disable_tunnel_HXX_
