
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_ProxyInterface_HXX_
#define INCLUDE_vnx_ProxyInterface_HXX_

#include <vnx/Type.h>
#include <vnx/package.hxx>
#include <vnx/Hash64.hpp>
#include <vnx/Session.hxx>


namespace vnx {

struct VNX_EXPORT ProxyInterface {
	
	
	
	static const vnx::Hash64 VNX_TYPE_HASH;
	static const vnx::Hash64 VNX_CODE_HASH;
	
	static constexpr uint64_t VNX_TYPE_ID = 0xa03443ba28431859ull;
	
	ProxyInterface() {}
	
};


} // namespace vnx


namespace vnx {

} // vnx

#endif // INCLUDE_vnx_ProxyInterface_HXX_
