
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_RecorderStatus_HXX_
#define INCLUDE_vnx_RecorderStatus_HXX_

#include <vnx/package.hxx>
#include <vnx/RecordHeader.hxx>
#include <vnx/Value.h>


namespace vnx {

class VNX_EXPORT RecorderStatus : public ::vnx::Value {
public:
	
	std::string file_name;
	vnx::bool_t is_recording = 0;
	vnx::float64_t bandwidth = 0;
	vnx::float64_t sample_rate = 0;
	vnx::float64_t loss_factor = 0;
	::vnx::RecordHeader header;
	
	typedef ::vnx::Value Super;
	
	static const vnx::Hash64 VNX_TYPE_HASH;
	static const vnx::Hash64 VNX_CODE_HASH;
	
	static constexpr uint64_t VNX_TYPE_ID = 0xc79edae794af8704ull;
	
	RecorderStatus() {}
	
	vnx::Hash64 get_type_hash() const override;
	std::string get_type_name() const override;
	const vnx::TypeCode* get_type_code() const override;
	
	static std::shared_ptr<RecorderStatus> create();
	std::shared_ptr<vnx::Value> clone() const override;
	
	void read(vnx::TypeInput& _in, const vnx::TypeCode* _type_code, const uint16_t* _code) override;
	void write(vnx::TypeOutput& _out, const vnx::TypeCode* _type_code, const uint16_t* _code) const override;
	
	void read(std::istream& _in) override;
	void write(std::ostream& _out) const override;
	
	template<typename T>
	void accept_generic(T& _visitor) const;
	void accept(vnx::Visitor& _visitor) const override;
	
	vnx::Object to_object() const override;
	void from_object(const vnx::Object& object) override;
	
	vnx::Variant get_field(const std::string& name) const override;
	void set_field(const std::string& name, const vnx::Variant& value) override;
	
	friend std::ostream& operator<<(std::ostream& _out, const RecorderStatus& _value);
	friend std::istream& operator>>(std::istream& _in, RecorderStatus& _value);
	
	static const vnx::TypeCode* static_get_type_code();
	static std::shared_ptr<vnx::TypeCode> static_create_type_code();
	
protected:
	std::shared_ptr<vnx::Value> vnx_call_switch(std::shared_ptr<const vnx::Value> _method) override;
	
};

template<typename T>
void RecorderStatus::accept_generic(T& _visitor) const {
	_visitor.template type_begin<RecorderStatus>(6);
	_visitor.type_field("file_name", 0); _visitor.accept(file_name);
	_visitor.type_field("is_recording", 1); _visitor.accept(is_recording);
	_visitor.type_field("bandwidth", 2); _visitor.accept(bandwidth);
	_visitor.type_field("sample_rate", 3); _visitor.accept(sample_rate);
	_visitor.type_field("loss_factor", 4); _visitor.accept(loss_factor);
	_visitor.type_field("header", 5); _visitor.accept(header);
	_visitor.template type_end<RecorderStatus>(6);
}


} // namespace vnx


namespace vnx {

} // vnx

#endif // INCLUDE_vnx_RecorderStatus_HXX_
