
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_GatewayInterface_HXX_
#define INCLUDE_vnx_GatewayInterface_HXX_

#include <vnx/Type.h>
#include <vnx/package.hxx>
#include <vnx/Request.hxx>


namespace vnx {

struct VNX_EXPORT GatewayInterface {
	
	
	
	static const vnx::Hash64 VNX_TYPE_HASH;
	static const vnx::Hash64 VNX_CODE_HASH;
	
	static constexpr uint64_t VNX_TYPE_ID = 0x433227325bd5879eull;
	
	GatewayInterface() {}
	
};


} // namespace vnx


namespace vnx {

} // vnx

#endif // INCLUDE_vnx_GatewayInterface_HXX_
