
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_Player_CLIENT_HXX_
#define INCLUDE_vnx_Player_CLIENT_HXX_

#include <vnx/Client.h>
#include <vnx/Module.h>
#include <vnx/RecordHeader.hxx>
#include <vnx/TopicPtr.hpp>


namespace vnx {

class PlayerClient : public vnx::Client {
public:
	PlayerClient(const std::string& service_name);
	
	PlayerClient(vnx::Hash64 service_addr);
	
	::vnx::RecordHeader get_info();
	
	void play();
	
	void play_async();
	
	void pause();
	
	void pause_async();
	
	void toggle();
	
	void toggle_async();
	
	void stop();
	
	void stop_async();
	
	void set_speed(const vnx::float64_t& speed = 0);
	
	void set_speed_async(const vnx::float64_t& speed = 0);
	
	void seek_by_count(const int64_t& delta_count = 0);
	
	void seek_by_count_async(const int64_t& delta_count = 0);
	
	void seek_by_time(const int64_t& delta_us = 0);
	
	void seek_by_time_async(const int64_t& delta_us = 0);
	
	void seek_to_position(const vnx::float64_t& position = 0);
	
	void seek_to_position_async(const vnx::float64_t& position = 0);
	
	void seek_to_time(const int64_t& time_us = 0);
	
	void seek_to_time_async(const int64_t& time_us = 0);
	
	::vnx::Object vnx_get_config_object();
	
	::vnx::Variant vnx_get_config(const std::string& name = "");
	
	void vnx_set_config_object(const ::vnx::Object& config = ::vnx::Object());
	
	void vnx_set_config_object_async(const ::vnx::Object& config = ::vnx::Object());
	
	void vnx_set_config(const std::string& name = "", const ::vnx::Variant& value = ::vnx::Variant());
	
	void vnx_set_config_async(const std::string& name = "", const ::vnx::Variant& value = ::vnx::Variant());
	
	::vnx::TypeCode vnx_get_type_code();
	
	std::shared_ptr<const ::vnx::ModuleInfo> vnx_get_module_info();
	
	void vnx_restart();
	
	void vnx_restart_async();
	
	void vnx_stop();
	
	void vnx_stop_async();
	
	vnx::bool_t vnx_self_test();
	
};


} // namespace vnx

#endif // INCLUDE_vnx_Player_CLIENT_HXX_
