
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_Process_CLIENT_HXX_
#define INCLUDE_vnx_Process_CLIENT_HXX_

#include <vnx/Client.h>
#include <vnx/LogMsg.hxx>
#include <vnx/Module.h>
#include <vnx/ModuleInfo.hxx>
#include <vnx/ProcessInfo.hxx>
#include <vnx/TimeControl.hxx>
#include <vnx/TimeSync.hxx>
#include <vnx/TopicInfo.hxx>
#include <vnx/Variant.hpp>


namespace vnx {

class ProcessClient : public vnx::Client {
public:
	ProcessClient(const std::string& service_name);
	
	ProcessClient(vnx::Hash64 service_addr);
	
	std::string get_name();
	
	::vnx::TimeSync get_sync_time();
	
	std::vector<::vnx::TopicInfo> get_topic_info(const vnx::bool_t& include_domains = 0);
	
	std::vector<::vnx::ModuleInfo> get_module_info();
	
	::vnx::ProcessInfo get_process_info();
	
	::vnx::Variant get_global_config(const std::string& key = "");
	
	void set_global_config(const std::string& key = "", const ::vnx::Variant& value = ::vnx::Variant());
	
	void set_global_config_async(const std::string& key = "", const ::vnx::Variant& value = ::vnx::Variant());
	
	void reload_config();
	
	void reload_config_async();
	
	void pause_log();
	
	void pause_log_async();
	
	void resume_log();
	
	void resume_log_async();
	
	void set_debug(const int32_t& level = 0);
	
	void set_debug_async(const int32_t& level = 0);
	
	void show_error_log();
	
	void show_error_log_async();
	
	void grep_log(const std::string& expr = "");
	
	void grep_log_async(const std::string& expr = "");
	
	void journal_log(const std::string& expr = "");
	
	void journal_log_async(const std::string& expr = "");
	
	void ungrep_log();
	
	void ungrep_log_async();
	
	void trigger_shutdown();
	
	void trigger_shutdown_async();
	
	void self_test_all();
	
	void self_test_all_async();
	
	::vnx::Object vnx_get_config_object();
	
	::vnx::Variant vnx_get_config(const std::string& name = "");
	
	void vnx_set_config_object(const ::vnx::Object& config = ::vnx::Object());
	
	void vnx_set_config_object_async(const ::vnx::Object& config = ::vnx::Object());
	
	void vnx_set_config(const std::string& name = "", const ::vnx::Variant& value = ::vnx::Variant());
	
	void vnx_set_config_async(const std::string& name = "", const ::vnx::Variant& value = ::vnx::Variant());
	
	::vnx::TypeCode vnx_get_type_code();
	
	std::shared_ptr<const ::vnx::ModuleInfo> vnx_get_module_info();
	
	void vnx_restart();
	
	void vnx_restart_async();
	
	void vnx_stop();
	
	void vnx_stop_async();
	
	vnx::bool_t vnx_self_test();
	
};


} // namespace vnx

#endif // INCLUDE_vnx_Process_CLIENT_HXX_
