
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_RecorderBase_HXX_
#define INCLUDE_vnx_RecorderBase_HXX_

#include <vnx/package.hxx>
#include <vnx/Hash64.hpp>
#include <vnx/Module.h>
#include <vnx/TopicPtr.hpp>


namespace vnx {

class VNX_EXPORT RecorderBase : public ::vnx::Module {
public:
	
	::vnx::TopicPtr output_status = "vnx.recorder_status";
	std::string filename;
	int32_t max_queue_ms = 1000;
	int32_t flush_interval_ms = 1000;
	int32_t header_size = 262144;
	int32_t block_size = 4096;
	std::vector<std::string> topics;
	std::string proxy_name;
	::vnx::Hash64 receive_tunnel;
	
	typedef ::vnx::Module Super;
	
	static const vnx::Hash64 VNX_TYPE_HASH;
	static const vnx::Hash64 VNX_CODE_HASH;
	
	static constexpr uint64_t VNX_TYPE_ID = 0x1325106a28614e06ull;
	
	RecorderBase(const std::string& _vnx_name);
	
	vnx::Hash64 get_type_hash() const override;
	std::string get_type_name() const override;
	const vnx::TypeCode* get_type_code() const override;
	
	void read(std::istream& _in) override;
	void write(std::ostream& _out) const override;
	
	template<typename T>
	void accept_generic(T& _visitor) const;
	void accept(vnx::Visitor& _visitor) const override;
	
	vnx::Object to_object() const override;
	void from_object(const vnx::Object& object) override;
	
	vnx::Variant get_field(const std::string& name) const override;
	void set_field(const std::string& name, const vnx::Variant& value) override;
	
	friend std::ostream& operator<<(std::ostream& _out, const RecorderBase& _value);
	friend std::istream& operator>>(std::istream& _in, RecorderBase& _value);
	
	static const vnx::TypeCode* static_get_type_code();
	static std::shared_ptr<vnx::TypeCode> static_create_type_code();
	
protected:
	using Super::handle;
	
	
	void vnx_handle_switch(std::shared_ptr<const vnx::Value> _value) override;
	std::shared_ptr<vnx::Value> vnx_call_switch(std::shared_ptr<const vnx::Value> _method, const vnx::request_id_t& _request_id) override;
	
};

template<typename T>
void RecorderBase::accept_generic(T& _visitor) const {
	_visitor.template type_begin<RecorderBase>(9);
	_visitor.type_field("output_status", 0); _visitor.accept(output_status);
	_visitor.type_field("filename", 1); _visitor.accept(filename);
	_visitor.type_field("max_queue_ms", 2); _visitor.accept(max_queue_ms);
	_visitor.type_field("flush_interval_ms", 3); _visitor.accept(flush_interval_ms);
	_visitor.type_field("header_size", 4); _visitor.accept(header_size);
	_visitor.type_field("block_size", 5); _visitor.accept(block_size);
	_visitor.type_field("topics", 6); _visitor.accept(topics);
	_visitor.type_field("proxy_name", 7); _visitor.accept(proxy_name);
	_visitor.type_field("receive_tunnel", 8); _visitor.accept(receive_tunnel);
	_visitor.template type_end<RecorderBase>(9);
}


} // namespace vnx


namespace vnx {

} // vnx

#endif // INCLUDE_vnx_RecorderBase_HXX_
