
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_RecordIndex_HXX_
#define INCLUDE_vnx_RecordIndex_HXX_

#include <vnx/package.hxx>
#include <vnx/Value.h>
#include <vnx/record_index_entry_t.hxx>


namespace vnx {

class VNX_EXPORT RecordIndex : public ::vnx::Value {
public:
	
	int64_t prev_block = -1;
	int64_t next_block = -1;
	std::vector<::vnx::record_index_entry_t> index;
	
	typedef ::vnx::Value Super;
	
	static const vnx::Hash64 VNX_TYPE_HASH;
	static const vnx::Hash64 VNX_CODE_HASH;
	
	static constexpr uint64_t VNX_TYPE_ID = 0xe361371e3c5531e9ull;
	
	RecordIndex() {}
	
	vnx::Hash64 get_type_hash() const override;
	std::string get_type_name() const override;
	const vnx::TypeCode* get_type_code() const override;
	
	static std::shared_ptr<RecordIndex> create();
	std::shared_ptr<vnx::Value> clone() const override;
	
	void read(vnx::TypeInput& _in, const vnx::TypeCode* _type_code, const uint16_t* _code) override;
	void write(vnx::TypeOutput& _out, const vnx::TypeCode* _type_code, const uint16_t* _code) const override;
	
	void read(std::istream& _in) override;
	void write(std::ostream& _out) const override;
	
	template<typename T>
	void accept_generic(T& _visitor) const;
	void accept(vnx::Visitor& _visitor) const override;
	
	vnx::Object to_object() const override;
	void from_object(const vnx::Object& object) override;
	
	vnx::Variant get_field(const std::string& name) const override;
	void set_field(const std::string& name, const vnx::Variant& value) override;
	
	friend std::ostream& operator<<(std::ostream& _out, const RecordIndex& _value);
	friend std::istream& operator>>(std::istream& _in, RecordIndex& _value);
	
	static const vnx::TypeCode* static_get_type_code();
	static std::shared_ptr<vnx::TypeCode> static_create_type_code();
	
protected:
	std::shared_ptr<vnx::Value> vnx_call_switch(std::shared_ptr<const vnx::Value> _method) override;
	
};

template<typename T>
void RecordIndex::accept_generic(T& _visitor) const {
	_visitor.template type_begin<RecordIndex>(3);
	_visitor.type_field("prev_block", 0); _visitor.accept(prev_block);
	_visitor.type_field("next_block", 1); _visitor.accept(next_block);
	_visitor.type_field("index", 2); _visitor.accept(index);
	_visitor.template type_end<RecordIndex>(3);
}


} // namespace vnx


namespace vnx {

} // vnx

#endif // INCLUDE_vnx_RecordIndex_HXX_
