
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_TimeServerBase_HXX_
#define INCLUDE_vnx_TimeServerBase_HXX_

#include <vnx/package.hxx>
#include <vnx/Hash64.hpp>
#include <vnx/Module.h>


namespace vnx {

class VNX_EXPORT TimeServerBase : public ::vnx::Module {
public:
	
	::vnx::Hash64 remote_tunnel;
	int32_t interval_ms = 200;
	int32_t inv_gain = 100;
	
	typedef ::vnx::Module Super;
	
	static const vnx::Hash64 VNX_TYPE_HASH;
	static const vnx::Hash64 VNX_CODE_HASH;
	
	static constexpr uint64_t VNX_TYPE_ID = 0x473fc7e0942fb246ull;
	
	TimeServerBase(const std::string& _vnx_name);
	
	vnx::Hash64 get_type_hash() const override;
	std::string get_type_name() const override;
	const vnx::TypeCode* get_type_code() const override;
	
	void read(std::istream& _in) override;
	void write(std::ostream& _out) const override;
	
	template<typename T>
	void accept_generic(T& _visitor) const;
	void accept(vnx::Visitor& _visitor) const override;
	
	vnx::Object to_object() const override;
	void from_object(const vnx::Object& object) override;
	
	vnx::Variant get_field(const std::string& name) const override;
	void set_field(const std::string& name, const vnx::Variant& value) override;
	
	friend std::ostream& operator<<(std::ostream& _out, const TimeServerBase& _value);
	friend std::istream& operator>>(std::istream& _in, TimeServerBase& _value);
	
	static const vnx::TypeCode* static_get_type_code();
	static std::shared_ptr<vnx::TypeCode> static_create_type_code();
	
protected:
	using Super::handle;
	
	
	void vnx_handle_switch(std::shared_ptr<const vnx::Value> _value) override;
	std::shared_ptr<vnx::Value> vnx_call_switch(std::shared_ptr<const vnx::Value> _method, const vnx::request_id_t& _request_id) override;
	
};

template<typename T>
void TimeServerBase::accept_generic(T& _visitor) const {
	_visitor.template type_begin<TimeServerBase>(3);
	_visitor.type_field("remote_tunnel", 0); _visitor.accept(remote_tunnel);
	_visitor.type_field("interval_ms", 1); _visitor.accept(interval_ms);
	_visitor.type_field("inv_gain", 2); _visitor.accept(inv_gain);
	_visitor.template type_end<TimeServerBase>(3);
}


} // namespace vnx


namespace vnx {

} // vnx

#endif // INCLUDE_vnx_TimeServerBase_HXX_
