
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_addons_CompressedValue_HXX_
#define INCLUDE_vnx_addons_CompressedValue_HXX_

#include <vnx/addons/package.hxx>
#include <vnx/Value.h>


namespace vnx {
namespace addons {

class VNX_ADDONS_EXPORT CompressedValue : public ::vnx::Value {
public:
	
	
	typedef ::vnx::Value Super;
	
	static const vnx::Hash64 VNX_TYPE_HASH;
	static const vnx::Hash64 VNX_CODE_HASH;
	
	static constexpr uint64_t VNX_TYPE_ID = 0x50c46e244bd9765dull;
	
	CompressedValue() {}
	
	vnx::Hash64 get_type_hash() const override;
	std::string get_type_name() const override;
	const vnx::TypeCode* get_type_code() const override;
	
	virtual std::shared_ptr<const ::vnx::Value> decompress() const;
	virtual std::shared_ptr<const ::vnx::Value> vnx_decompress() const;
	
	static std::shared_ptr<CompressedValue> create();
	std::shared_ptr<vnx::Value> clone() const override;
	
	void read(vnx::TypeInput& _in, const vnx::TypeCode* _type_code, const uint16_t* _code) override;
	void write(vnx::TypeOutput& _out, const vnx::TypeCode* _type_code, const uint16_t* _code) const override;
	
	void read(std::istream& _in) override;
	void write(std::ostream& _out) const override;
	
	template<typename T>
	void accept_generic(T& _visitor) const;
	void accept(vnx::Visitor& _visitor) const override;
	
	vnx::Object to_object() const override;
	void from_object(const vnx::Object& object) override;
	
	vnx::Variant get_field(const std::string& name) const override;
	void set_field(const std::string& name, const vnx::Variant& value) override;
	
	friend std::ostream& operator<<(std::ostream& _out, const CompressedValue& _value);
	friend std::istream& operator>>(std::istream& _in, CompressedValue& _value);
	
	static const vnx::TypeCode* static_get_type_code();
	static std::shared_ptr<vnx::TypeCode> static_create_type_code();
	
protected:
	std::shared_ptr<vnx::Value> vnx_call_switch(std::shared_ptr<const vnx::Value> _method) override;
	
};

template<typename T>
void CompressedValue::accept_generic(T& _visitor) const {
	_visitor.template type_begin<CompressedValue>(0);
	_visitor.template type_end<CompressedValue>(0);
}


} // namespace vnx
} // namespace addons


namespace vnx {

} // vnx

#endif // INCLUDE_vnx_addons_CompressedValue_HXX_
