
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_addons_HttpComponent_CLIENT_HXX_
#define INCLUDE_vnx_addons_HttpComponent_CLIENT_HXX_

#include <vnx/Client.h>
#include <vnx/addons/HttpData.hxx>
#include <vnx/addons/HttpRequest.hxx>
#include <vnx/addons/HttpResponse.hxx>


namespace vnx {
namespace addons {

class HttpComponentClient : public vnx::Client {
public:
	HttpComponentClient(const std::string& service_name);
	
	HttpComponentClient(vnx::Hash64 service_addr);
	
	std::shared_ptr<const ::vnx::addons::HttpResponse> http_request(std::shared_ptr<const ::vnx::addons::HttpRequest> request = nullptr, const std::string& sub_path = "");
	
	std::shared_ptr<const ::vnx::addons::HttpData> http_request_chunk(std::shared_ptr<const ::vnx::addons::HttpRequest> request = nullptr, const std::string& sub_path = "", const int64_t& offset = 0, const int64_t& max_bytes = 0);
	
};


} // namespace vnx
} // namespace addons

#endif // INCLUDE_vnx_addons_HttpComponent_CLIENT_HXX_
