
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_addons_HttpChunk_HXX_
#define INCLUDE_vnx_addons_HttpChunk_HXX_

#include <vnx/addons/package.hxx>
#include <vnx/addons/HttpData.hxx>


namespace vnx {
namespace addons {

class VNX_ADDONS_EXPORT HttpChunk : public ::vnx::addons::HttpData {
public:
	
	uint64_t id = 0;
	
	typedef ::vnx::addons::HttpData Super;
	
	static const vnx::Hash64 VNX_TYPE_HASH;
	static const vnx::Hash64 VNX_CODE_HASH;
	
	static constexpr uint64_t VNX_TYPE_ID = 0x34dddafe7f03674bull;
	
	HttpChunk() {}
	
	vnx::Hash64 get_type_hash() const override;
	std::string get_type_name() const override;
	const vnx::TypeCode* get_type_code() const override;
	
	static std::shared_ptr<HttpChunk> create();
	std::shared_ptr<vnx::Value> clone() const override;
	
	void read(vnx::TypeInput& _in, const vnx::TypeCode* _type_code, const uint16_t* _code) override;
	void write(vnx::TypeOutput& _out, const vnx::TypeCode* _type_code, const uint16_t* _code) const override;
	
	void read(std::istream& _in) override;
	void write(std::ostream& _out) const override;
	
	template<typename T>
	void accept_generic(T& _visitor) const;
	void accept(vnx::Visitor& _visitor) const override;
	
	vnx::Object to_object() const override;
	void from_object(const vnx::Object& object) override;
	
	vnx::Variant get_field(const std::string& name) const override;
	void set_field(const std::string& name, const vnx::Variant& value) override;
	
	friend std::ostream& operator<<(std::ostream& _out, const HttpChunk& _value);
	friend std::istream& operator>>(std::istream& _in, HttpChunk& _value);
	
	static const vnx::TypeCode* static_get_type_code();
	static std::shared_ptr<vnx::TypeCode> static_create_type_code();
	
protected:
	std::shared_ptr<vnx::Value> vnx_call_switch(std::shared_ptr<const vnx::Value> _method) override;
	
};

template<typename T>
void HttpChunk::accept_generic(T& _visitor) const {
	_visitor.template type_begin<HttpChunk>(3);
	_visitor.type_field("data", 0); _visitor.accept(data);
	_visitor.type_field("is_eof", 1); _visitor.accept(is_eof);
	_visitor.type_field("id", 2); _visitor.accept(id);
	_visitor.template type_end<HttpChunk>(3);
}


} // namespace vnx
} // namespace addons


namespace vnx {

} // vnx

#endif // INCLUDE_vnx_addons_HttpChunk_HXX_
