
// AUTO GENERATED by vnxcppcodegen

#ifndef INCLUDE_vnx_addons_HttpComponent_HXX_
#define INCLUDE_vnx_addons_HttpComponent_HXX_

#include <vnx/Type.h>
#include <vnx/addons/package.hxx>
#include <vnx/addons/HttpData.hxx>
#include <vnx/addons/HttpRequest.hxx>
#include <vnx/addons/HttpResponse.hxx>


namespace vnx {
namespace addons {

struct VNX_ADDONS_EXPORT HttpComponent {
	
	
	
	static const vnx::Hash64 VNX_TYPE_HASH;
	static const vnx::Hash64 VNX_CODE_HASH;
	
	static constexpr uint64_t VNX_TYPE_ID = 0x6ddcddab3925b2efull;
	
	HttpComponent() {}
	
};


} // namespace vnx
} // namespace addons


namespace vnx {

} // vnx

#endif // INCLUDE_vnx_addons_HttpComponent_HXX_
